# Generated by Django 6.0.3 on 2026-04-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus_date', models.DateField()),
                ('role', models.CharField(choices=[('main', 'Main'), ('secondary', 'Secondary')], max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_assignments', to='cases.case')),
            ],
            options={
                'ordering': ('-focus_date', 'role', 'order'),
                'constraints': [models.UniqueConstraint(fields=('focus_date', 'case'), name='uniq_focus_assignment_per_case_per_day'), models.UniqueConstraint(fields=('focus_date', 'role', 'order'), name='uniq_focus_assignment_slot_per_day')],
            },
        ),
    ]
