# Generated by Django 6.0.3 on 2026-04-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('inbox', 'Inbox'), ('active', 'Active'), ('waiting', 'Waiting'), ('done', 'Done')], default='inbox', max_length=16)),
                ('clarity', models.CharField(choices=[('clear', 'Clear'), ('fuzzy', 'Fuzzy')], default='fuzzy', max_length=16)),
                ('work_type', models.CharField(choices=[('build', 'Build'), ('debug', 'Debug'), ('research', 'Research'), ('admin', 'Admin'), ('reply', 'Reply')], default='build', max_length=16)),
                ('effort', models.CharField(choices=[('quick', 'Quick'), ('medium', 'Medium'), ('deep', 'Deep')], default='medium', max_length=16)),
                ('energy', models.CharField(choices=[('shallow', 'Shallow'), ('deep', 'Deep')], default='shallow', max_length=16)),
                ('next_step', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PrivateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_notes', to='cases.case')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SpecDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('markdown_body', models.TextField(blank=True)),
                ('rendered_cache', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_document', to='cases.case')),
            ],
            options={
                'ordering': ('case_id',),
            },
        ),
    ]
