# Generated by Django 6.0.3 on 2026-05-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='stale_ack_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='stale_acked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
