# Generated by Django 6.0.3 on 2026-04-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=64)),
                ('promoted', models.BooleanField(default=False)),
                ('rationale', models.TextField(blank=True)),
                ('alternatives', models.TextField(blank=True)),
                ('consequence', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='cases.case')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
