# Generated by Django 6.0.3 on 2026-04-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('clickup', 'ClickUp'), ('url', 'URL'), ('note', 'Note'), ('other', 'Other')], default='manual', max_length=16)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('raw_body', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('raw_metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('triage_state', models.CharField(choices=[('new', 'New'), ('doing_now', 'Doing now'), ('converted', 'Converted'), ('parked', 'Parked'), ('waiting', 'Waiting'), ('done', 'Done'), ('archived', 'Archived')], default='new', max_length=16)),
                ('converted_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inbox_item', to='cases.case')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
    ]
