# Generated by Django 6.0.3 on 2026-04-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='completion_note',
            field=models.TextField(blank=True),
        ),
    ]
