# Generated by Django 6.0.3 on 2026-05-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_inboxitem_completion_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='triage_state',
            field=models.CharField(choices=[('new', 'New'), ('doing_now', 'Doing now'), ('converted', 'Converted'), ('parked', 'Set aside'), ('waiting', 'Waiting on'), ('done', 'Done'), ('archived', 'Archived')], default='new', max_length=16),
        ),
    ]
