# Generated by Django 6.0.3 on 2026-07-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_phase1_multi_user_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxitem',
            name='raw_metadata_snapshot',
        ),
        migrations.RemoveField(
            model_name='inboxitem',
            name='source_reference',
        ),
    ]
