# Generated by Django 6.0.3 on 2026-04-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('clickup', 'ClickUp'), ('url', 'URL'), ('manual', 'Manual'), ('other', 'Other')], max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('external_title_snapshot', models.CharField(blank=True, max_length=255)),
                ('external_status_snapshot', models.CharField(blank=True, max_length=255)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='cases.case')),
                ('inbox_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='inbox.inboxitem')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
